- name: Build Debug APK
        run: gradle :app:assembleDebug --no-daemon -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Scan2PDF-Project-APK
          # با استفاده از این علامت (**) به گیت‌هاب می‌گیم هر جا فایل apk پیدا کرد برامون بیاره
          path: "**/build/outputs/apk/debug/*.apk"
